source("element.R")
source("dcb_L2.R")
source("dcb_L3.R")
source("dcb_L4.R")
source("dcb_L5.R")
source("dcb_L6.R")
source("dcb_L7.R")
source("dcb_L8.R")
source("dcb_L9.R")
source("dcb_JL.R")

for (i in 19001:19151) {
  # dcb_L2(i)
  dcb_L3(i,-1)
  dcb_L4(i,-1)
  dcb_L5(i,-1)
  dcb_L6(i,-1)
  dcb_L7(i,-1)
  dcb_L8(i,-1)
  dcb_L9(i,-1)
  # dcb_JL(i,-1)
}

max_n=max(as.integer(dcb$n))
dcb_L2(max_n)
dcb_L3(max_n,number_of_core)
dcb_L4(max_n,number_of_core)
dcb_L5(max_n,number_of_core)
dcb_L6(max_n,number_of_core)
dcb_L7(max_n,number_of_core)
dcb_L8(max_n,number_of_core)
dcb_L9(max_n,number_of_core)
dcb_JL(max_n,number_of_core)
